accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='accounts'
urlpatterns = [
    
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name="register"),
    path('profile/',views.profile,name='profile'),
    path('blogs/',views.profile_blogs,name='profile_blogs'),
    path('edit-profile/',views.edit_profile,name="edit_profile"),
    path('publish/<int:blog_id>/',views.publish_now,name='publish_now'),
    

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('accounts/',include('accounts.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    
    path('',views.index,name="index"),
    path('add-post/',views.add_post,name='add_post'),
    path('view-post/<slug:slug>/',views.view_post,name='view_post'),
    path('edit-post/<int:blog_id>/',views.edit_post,name='edit_post'),
    path('delete-post/<int:blog_id>',views.delete_post,name='delete_post'),
    path('category/<slug:slug>/',views.view_category_post,name='view_category_post'),
    path('like-post/<int:blog_id>/',views.like_post,name='like_post'),
    # path('search/',views.nav_search,name='nav_search'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=60)
    slug=models.SlugField(unique=True,) 

    class Meta:
        verbose_name_plural='Categories' 

    def __str__(self):
        return self.name





class Tag(models.Model):
    name=models.CharField(max_length=30)    
    slug=models.SlugField(unique=True,)

    def __str__(self):
        return self.name.title()
    
    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.name)
        super().save(*args,**kwargs)


class Post(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(unique=True,max_length=100)
    content=models.TextField()
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False)
    category=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,related_name='posts')
    tag=models.ManyToManyField(Tag,blank=True)
    image=models.ImageField(upload_to='images/',default="No_Image_Available.jpg")

    def __str__(self):
        return self.title
    
    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug=slugify(self.title)
        super().save(*args,**kwargs)




class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments")
    text=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return f"Comment by {self.author} on post {self.post}"
    
class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name="likes")
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} likes {self.post}"

blogs/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
    tag_input=forms.CharField(required=False,help_text="Multiple tags, seperate by commas",label="Tag")
    class Meta:
        model=Post
        fields=['title','content','category','tag_input','image','published']
        labels={'published':'Publish',}
        help_texts={'published':"Tick, if you want to publish now",}
        


class CommentsForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['text',]
        labels={'text':"Comment below"}
        widgets={'text':forms.Textarea(attrs={'cols':10,'rows':5,})}

blogs/views.py
from django.shortcuts import render,redirect
from .forms import PostForm,CommentsForm
from .models import Post,Tag,Category,Like
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
    post_list=Post.objects.filter(published=True).order_by('-updated_at')
    
    #for blog search functionality
    item=request.GET.get('input-search')
    if item != '' and item is not None:
        post_list=Post.objects.filter(title__icontains=item)

    context={'post_list':post_list}
    return render(request,'blog/index.html',context)
    
#normal function 
def string_to_tags(tag_string):
    tags=[tag.strip().lower() for tag in tag_string.split(',') if tag.strip()]
    
    return tags
    

@login_required
def add_post(request):
    if request.method=='POST':
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            post_obj=form.save(commit=False)
            post_obj.author=request.user
            post_obj.save()
            tag_string=form.cleaned_data.get('tag_input')
            if tag_string:
                tags=string_to_tags(tag_string)
                print(type(tags))
                for tag in tags:
                    tag_obj,created=Tag.objects.get_or_create(name=tag)
                    post_obj.tag.add(tag_obj)

                

            return redirect('blog:index')
    form=PostForm()
    context={'form':form}
    return render(request,'blog/add_post.html',context)

@login_required
def edit_post(request,blog_id):
    # instance=Post.objects.get(id=blog_id)
    instance=get_object_or_404(Post,id=blog_id)
    if instance.author!=request.user:
        raise Http404
    if request.POST:
        form=PostForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            post_obj=form.save()
            tag_string=form.cleaned_data['tag_input']
            print(tag_string)
            if tag_string:
                tags=string_to_tags(tag_string)
                for tag in tags:
                    tag_obj,created=Tag.objects.get_or_create(name=tag)
                    post_obj.tag.add(tag_obj)


            return redirect('blog:index')
    else:
        tag_string=', '.join(instance.tag.values_list('name',flat=True))
        form=PostForm(instance=instance,initial={'tag_input':tag_string})
        context={'form':form}
        return render(request,'blog/edit_post.html',context)


def view_post(request, slug):
    instance = get_object_or_404(Post, slug=slug)  # More efficient than `.get()`
    
    comment_form = CommentsForm(request.POST or None)  # More efficient form handling
    
    if request.method == "POST" and comment_form.is_valid():
        comment_obj = comment_form.save(commit=False)
        comment_obj.post = instance
        comment_obj.author = request.user
        comment_obj.save()
        return redirect('blog:view_post', slug=slug)  # PRG Pattern to prevent duplicate submission

    context = {
        'post': instance,
        'comment_form': comment_form,
        'comments': instance.comments.all(),
        'tags': instance.tag.all(),
        'like_count': instance.likes.count()  # More efficient count retrieval
    }
    
    return render(request, 'blog/view_post.html', context)
@login_required
def delete_post(request,blog_id):

    instance=Post.objects.get(id=blog_id)
    if instance.author!=request.user:
        raise Http404

    instance.delete()
    return redirect('blog:index')

def view_category_post(request,slug):
    category=Category.objects.get(slug=slug)
    posts=category.posts.filter(published=True).order_by('-updated_at')
    context={'category':category,'posts':posts}
    return render(request,'blog/category_page.html',context)

@login_required
def like_post(request,blog_id):
    instance=Post.objects.get(id=blog_id)
    if not Like.objects.filter(user=request.user,post=instance).exists():
        Like.objects.create(user=request.user,post=instance)
    return redirect('blog:view_post',slug=instance.slug)


    

blogs/templates/blog/add_post.html
{% extends 'blog/base.html' %}

{% load django_bootstrap5 %}


{% block content %}
<div class="container">

    <div class="row">
        <div class="col-md-6">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type='submit' content="Add Blog" %}
            </form>

        </div>
        

    </div>

    
</div>

{% endblock %}    

blogs/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'blog:index' %}">Blog Website</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:add_post' %}">Add Blog</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Category
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for category in categories %}
                  <li><a class="dropdown-item" href="{% url 'blog:view_category_post' category.slug %}">{{category.name}}</a></li>
                  <!-- <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                    {% endfor %}
                </ul>
              </li>
              


            </ul>
            <div class="d-flex justify-content-end">
                
                {% if user.is_authenticated %}
                <a href="{% url 'accounts:profile' %}"><h4 class="d-flex align-item-center me-2">Hi {{user.username}}</h4></a>
                {% endif %}
                <form action="{% url 'blog:index' %}"   class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="input-search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form action="{% url 'accounts:logout' %}" method="POST" class="btn-link">
                            {% csrf_token %}
                            {% bootstrap_button button_type='submit' content="logout" button_class="btn btn-link" %}

                        </form>
                      
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    {% endif %}
                  </ul>

            </div>
            
          </div>
        </div>
      </nav>
      <div class="pb-2 mb-2 border-bottom"></div>
    
    {% block page_header %}

    {% endblock page_header %}

    {% block content %}
    

    {% endblock %}
    
</body>
</html>

blogs/templates/blog/category_page.html
{% extends 'blog/base.html' %}

{% block page_header %}
<div class="container">

<h3>{{category.name}}</h3>
<hr>
{% endblock page_header %}


{% block content %}

<div class="row">
{% for post in posts %}

<div class="col-md-3">
    <div class="card" style="width: 18rem;">
        <img src="{{post.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <p class="card-text">{{post.content|slice:':80'}}...</p>
          <a href="{% url 'blog:view_post' post.slug %}" class="btn btn-primary">View Blog</a>
        </div>
      </div>

</div>

{% empty %}
<p>There are no blogs from {{category.name}} Category</p>
<p>You want to add new blog <a href="{% url 'blog:add_post' %}">Click here</a></p> 


{% endfor %}

</div>



</div>


{% endblock %}
    

blogs/templates/blog/edit_post.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}


{% block content %}
<div class="container">

<div class="row">
    <div class="col-md-6">
        <form action="" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type='submit' content="Edit Post" %}
        </form>

    </div>
    

</div>

</div>
{% endblock %}

blogs/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">


    <div class="row">
        {% for post in post_list %}
        <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                  <a href="{% url 'blog:view_category_post' post.category.slug  %}"><strong class="d-inline-block mb-2 text-primary">{{post.category}}</strong></a>
                  <h3 class="mb-0">
                    <a class="text-dark" href="{% url 'blog:view_post' post.slug %}">{{post.title}}</a>
                  </h3>
                  <div class="mb-1 text-muted">{{post.updated_at|date:'M d, Y'}}</div>
                  <p class="card-text mb-auto">{{post.content|slice:":50"}}...<a href="{% url 'blog:view_post' post.slug %}">Continue reading</a></p>
                  {% if post.author == user %}
                  <p>
                    <a href="{% url 'blog:edit_post' post.id %}" class="btn btn-primary me-2">Edit Blog</a>
                  <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-danger">Delete Blog</a>

                  </p>
                  
                  {% endif %}
                </div>
                
                <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]" style="width: 200px; height: 250px;" src="{{post.image.url}}" data-holder-rendered="true">
              </div>
          

        </div>
        {% empty %}
            <p>There are no Blog</p>
           
        {% endfor %}  
    </div>









</div>

{% endblock %}

blogs/templates/blog/view_post.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container my-4">
    <!-- Blog Post -->
    <div class="row">
        <div class="col-md-8">
            <article class="blog-post">
                <!-- Post Title -->
                <h2 class="display-4 mb-3">{{ post.title }}</h2>
                
                <!-- Post Meta (Author and Date) -->
                <p class="blog-post-meta mb-3">
                    <span>{{ post.updated_at|date:'M d, Y' }}</span> by 
                    <a href="#">{{ post.author.username }}</a>
                     
                     <a href="{% url 'blog:like_post' post.id %}"><button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up">Like<span> {{like_count}} </span></i> </button></a>
                </p>

                <!-- Edit and Delete Links (Visible only to the author) -->
                <div class="d-flex justify-content-between align-items-center">
                    {% if post.author == user %}
                <div class="d-flex justify-content-start mb-4">
                    <a href="{% url 'blog:edit_post' post.id %}" class="btn btn-primary me-2">Edit</a>
                    <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-danger">Delete</a>
                </div>
                {% endif %}
                <div  class="social-share d-flex mb-4 gap-2">
                    <p class="pe-2">Share this post:</p>
                    
                    <!-- Facebook -->
                    <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" class="btn btn-primary">
                        <i class="fab fa-facebook"></i> Facebook
                    </a>
                    <a href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}&text={{ post.title }}" target="_blank" class="btn btn-info">
                        <i class="fab fa-twitter"></i> Twitter
                    </a>
                    <a href="https://www.linkedin.com/shareArticle?url={{ request.build_absolute_uri }}&title={{ post.title }}" target="_blank" class="btn btn-secondary">
                        <i class="fab fa-linkedin"></i> LinkedIn
                    </a>

                </div>

                </div>
            
                

                
                
            </article>
        </div>

        <!-- Image and Content Section -->
        <div class="col-md-10">
            <div class="row">
                <div class="col-md-6">
                    <!-- Image Section -->
                    <img src="{{ post.image.url }}" class="img-fluid rounded border" alt="{{ post.title }}">
                </div>

                <div class="col-md-6">
                    <!-- Content Section -->
                    <p class="mt-4">{{ post.content }}</p>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <!-- Tags Section -->
    <div class="tags mb-4">
        {% for tag in tags %}
            <span class="badge bg-secondary me-2">{{ tag.name }}</span>
        {% empty %}
            <span class="badge bg-light">No Tags</span>
        {% endfor %}
    </div>

    <!-- Comments Section -->
    <div class="card mt-4">
        <div class="card-header">
            <strong>Comments</strong>
        </div>
        <div class="card-body">
            <ul class="list-group">
                {% for comment in comments %}
                    {% if comment.author.profile.profile_picture %}
                    <div class="list-group-item d-flex gap-2">
                        <img style="width: 30px; height: 30px; object-fit: cover;" class="rounded-circle" src="{{comment.author.profile.profile_picture.url}}" alt="">
                        {% else %}
                        <img style="width: 30px; height: 30px; object-fit: cover;" class="rounded-circle" src="/media/profile_pic/No_Image_Available.jpg" alt="Default image">
                        {% endif %}
                        <p> by {{comment.author.username}}</p>
                    <div class="d-block">
                        <small><li class="list-group-item">- {{ comment.text }}</li></small>
                            
                     </div>    
                        
                    </div>
                    
                    
                {% empty %}
                    <p class="text-muted">There are no comments yet.</p>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!-- Comment Form -->
    <div class="row mt-3">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                {% bootstrap_button button_type='submit' content="Add Comment" class="btn btn-success" %}
            </form>
        </div>
    </div>
</div>

{% endblock %}