accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='accounts'
urlpatterns = [
    
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name="register"),
    path('profile/',views.profile,name='profile'),
    path('blogs/',views.profile_blogs,name='profile_blogs'),
    path('edit-profile/',views.edit_profile,name="edit_profile"),
    path('publish/<int:blog_id>/',views.publish_now,name='publish_now'),
    

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('accounts/',include('accounts.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    
    path('',views.index,name="index"),
    path('add-post/',views.add_post,name='add_post'),
    path('view-post/<slug:slug>/',views.view_post,name='view_post'),
    path('edit-post/<int:blog_id>/',views.edit_post,name='edit_post'),
    path('delete-post/<int:blog_id>',views.delete_post,name='delete_post'),
    path('category/<slug:slug>/',views.view_category_post,name='view_category_post'),
    path('like-post/<int:blog_id>/',views.like_post,name='like_post'),
    # path('search/',views.nav_search,name='nav_search'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    date_of_birth=models.DateField(null=True,blank=True)
    bio=models.TextField(blank=True)
    profile_picture=models.ImageField(upload_to='profile_pic/',default="No_Image_Available.jpg",blank=True,null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

accounts/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['date_of_birth','bio','profile_picture']
        labels={'date_of_birth':'Date of birth','bio':'Bio','profile_picture':'Profile Picture'}
        widgets={'date_of_birth':forms.DateInput(attrs={'type':'date'})}

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .models import Profile
from blogs.models import Post
from .forms import ProfileForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method=='POST':
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            login(request,new_user)
            return redirect('blog:index')
        return render(request,'registration/register.html')
    else:
        form=UserCreationForm()
        context={'form':form}
        return render(request,'registration/register.html',context)

@login_required    
def profile(request):
    profile=Profile.objects.get(user=request.user)
    context={'profile':profile}
    return render(request,'profile.html',context)

@login_required    
def profile_blogs(request):
    profile=Profile.objects.get(user=request.user)
    #for draft blogs
    draft_blogs=profile.user.posts.filter(published=False)
    # for published blogs
    published_blogs=Post.objects.filter(author=profile.user,published=True)

    context={'draft_blogs':draft_blogs,'profile':profile,'published_blogs':published_blogs}


    return render(request,'profile_blogs.html',context)

@login_required    
def edit_profile(request):
    instance=Profile.objects.get(user=request.user)
    if request.method=="POST":
        form=ProfileForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:

        form=ProfileForm(instance=instance)
       
    return render(request,'edit_profile.html',{'form':form})


def publish_now(request,blog_id):
    blog=Post.objects.get(id=blog_id)
    blog.published=True
    blog.save()
    return redirect('accounts:profile_blogs')

accounts/templates/edit_profile.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block content %}

 {% include 'sidebar.html' %}
    
      
    <div class="col-md-8">
        <form action="{% url 'accounts:edit_profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_type="submit" content="Submit" %}
            

        </form>
        
        
         
    </div>

      
{% endblock %}

accounts/templates/profile.html
{% extends 'blog/base.html' %}

{% block content %}

 {% include 'sidebar.html' %}
      
      <div class="col-md-8">
        <!-- Profile Card -->
        <div class="card">
            <div class="card-header bg-primary text-white text-center">
                <h2>{{ profile.user.username }}'s Profile</h2>
            </div>
            <div class="card-body">
                <!-- Profile Picture -->
                {% if profile.profile_picture %}
                <div class="text-center mb-4">
                    <img src="{{profile.profile_picture.url}}" style="width: 150px; height: 150px; object-fit: cover;" class="rounded-circle" alt="Profile Picture" width="150">
                </div>
                {% else %}
                <div class="text-center mb-4">
                    <img src="/media/profile_pic/No_Image_Available.jpg" style="width: 150px; height: 150px; object-fit: cover;" class="rounded-circle" alt="Profile Picture" width="150">
                </div>

                {% endif %}
                <div class="mb-3">
                    <h5 class="d-inline ">Date of Birth : </h5> <span>{{profile.date_of_birth}}</span>

                </div>
                
                <!-- Bio Section -->
                <h4 class="mb-3">Bio</h4>
                <hr>
                <p>{{ profile.bio|default:"No bio provided." }}</p>
                
                <!-- Links (Edit Profile, etc.) -->
                <div class="mt-4 text-center">
                    <a href="{% url 'accounts:edit_profile' %}" class="btn btn-warning">Edit Profile</a>
                </div>
            </div>
        </div>
    </div>
</div>

      
{% endblock %}

accounts/templates/profile_blogs.html
{% extends 'blog/base.html' %}

{% block content %}
{% include 'sidebar.html' %}

<div class="col-md-8">
    <!-- Draft Blogs Section -->
    <div class="row">
        <h3>Your Draft Blog (Unpublished)</h3>
        <hr>
        {% for blog in draft_blogs %}
        <div class="col-md-4 mb-4">  <!-- Added mb-4 for spacing between cards -->
            <div class="card">
                <img src="{{blog.image.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{blog.title}}</h5>
                    <p class="card-text">{{blog.content|slice:':30'}}...</p>
                    <a href="{% url 'accounts:publish_now' blog.id %}" class="btn btn-primary">Publish now</a>
                    <a href="{% url 'blog:edit_post' blog.id %}" class="btn btn-primary">Edit Blog</a>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="col-12">
                <p>You have no drafts</p>
            </div>
        {% endfor %}
    </div>

    <!-- Published Blogs Section -->
    <div class="row">
        <h3>Your Published Blogs</h3>
        <hr>
        {% for blog in published_blogs %}
        <div class="col-md-4 mb-4"> <!-- Added mb-4 for spacing between cards -->
            <div class="card">
                <img src="{{blog.image.url}}" class="card-img-top"  alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{blog.title}}</h5>
                    <p class="card-text">{{blog.content|slice:':30'}}...</p>
                    <a href="{% url 'blog:edit_post' blog.id %}" class="btn btn-primary">Edit Blog</a>

                </div>
            </div>
        </div>
        {% empty %}
            <div class="col-12">
                <p>You have no Published Blogs</p>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

accounts/templates/sidebar.html
<div class="row">
    <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
          <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
          <span class="fs-4">Dashboard</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{% url 'accounts:profile' %}" class="nav-link active" aria-current="page">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
              Home
            </a>
          </li>
          <li>
            <a href="{% url 'accounts:profile_blogs' %}" class="nav-link text-white">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
              Your Blogs
            </a>
          </li>
          <!-- <li>
            <a href="#" class="nav-link text-white">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
              Orders
            </a>
          </li>
          <li>
            <a href="#" class="nav-link text-white">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
              Products
            </a>
          </li>
          <li>
            <a href="#" class="nav-link text-white">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
              Customers
            </a>
          </li> -->
        </ul>
        <hr>
        <div class="dropdown">
          <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>{{profile.user.username}}</strong>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
        </div>
      </div>